config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registration]
  resources :people
  resources :surveys do
    post "add_person", on: :member
    post "send_mail", on: :member
  end

  get "enforcements/edit", to: "enforcements#edit"
  get "enforcements/denied", to: "enforcements#denied"
  patch "enforcements/:id/update", to: "enforcements#update", as: :enforcement
  delete "enforcements/:id/delete", to: "enforcements#destroy", as: :enforcement_destroy

  root "surveys#index"
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :enforcements, dependent: :restrict_with_error
  has_many :surveys, through: :enforcements

  validates :email, presence: true, 'valid_email_2/email': { mx: true }, uniqueness: true
  validates :name, presence: true

  def to_s
    self.email
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def person_params
    params.require(:person).permit(:email, :name)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= form_with(model: person, local: true) do |form|
  - if person.errors.any?
    .alert.alert-warning.alert-dismissible.fade.show[role="alert"]
      = pluralize(person.errors.count, "erros")
      |  impedindo que o registro seja salvo
      hr/
      ul
        - person.errors.full_messages.each do |message|
          li
            = message
  .form-group
    = form.label :email
    = form.text_field :email, class: 'form-control'
  .form-group
    = form.label :name
    = form.text_field :name, class: 'form-control'
  = button_tag 'Salvar', type: 'submit', class: 'btn btn-primary'

app/views/people/edit.html.slim
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Editar membro
      .card-body
        = render 'form', person: @person
      .card-footer
        = link_to 'Voltar', people_path, class: 'btn btn-primary mr-2'
        = link_to 'Mostrar', @person, class: 'btn btn-primary mr-2'

app/views/people/index.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Membros
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-body
        .table-responsive
          table.table.table-striped.table-sm
            thead
              tr
                th Nome
                th Email
                th #
            tbody
              - @people.each do |person|
                tr
                  td
                    = person.name
                  td
                    = person.email
                  td
                    = link_to 'Exibir', person, class: 'btn btn-primary btn-sm mr-2'
                    = link_to 'Editar', edit_person_path(person), class: 'btn btn-primary btn-sm mr-2'
                    = link_to 'Deletar', person, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm mr-2'
      .card-footer
        = link_to 'Novo membro', new_person_path

app/views/people/new.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Membros
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Novo Membro
      .card-body
        = render 'form', person: @person
      .card-footer
        = link_to 'Voltar', people_path, class: 'btn btn-primary mr-2'

app/views/people/show.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Membros
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Visualizando membro
      .card-body
        p#notice
          = notice
        hr/
        p
          strong
            | Nome: 
          = @person.name
        hr/  
        p
          strong
            | Email: 
          = @person.email
        hr/
      .card-footer
        = link_to 'Voltar', people_path, class: 'btn btn-primary mr-2'
        = link_to 'Editar', edit_person_path(@person), class: 'btn btn-primary mr-2'