config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registration]
  resources :people
  resources :surveys do
    post "add_person", on: :member
    post "send_mail", on: :member
  end

  get "enforcements/edit", to: "enforcements#edit"
  get "enforcements/denied", to: "enforcements#denied"
  patch "enforcements/:id/update", to: "enforcements#update", as: :enforcement
  delete "enforcements/:id/delete", to: "enforcements#destroy", as: :enforcement_destroy

  root "surveys#index"
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :enforcements, dependent: :delete_all
  has_many :people, through: :enforcements

  validates_presence_of :question

  def send_request_mails
    self.people.each do |person|
      @enforcement = self.enforcements.find_by(person_id: person.id)
      SurveyMailer.with(enforcement: @enforcement).send_request.deliver_later
    end

    self.closed = true
    self.save
  end

  def send_result_mails
    self.people.each do |person|
      @enforcement = self.enforcements.find_by(person_id: person.id)
      SurveyMailer.with(enforcement: @enforcement).send_result.deliver_later
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_survey, only: [:show, :edit, :update, :destroy, :send_mail, :add_person]
  before_action :check_if_survey_is_closed, only: [:edit, :update]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @people_attrs = survey_params[:people]
    @people_attrs.delete_if { |email| email.empty? || email.blank? }
    @survey = Survey.new(survey_params.except(:people))

    respond_to do |format|
      if @survey.save
        @people_attrs.each do |person|
          person = Person.find(person.to_i)
          enforcement = @survey.enforcements.create(person_id: person.id)

          if !enforcement.save
            @survey.errors.messages[:email].append("#{person.email} já está sendo utilizado para esta pesquisa")

            format.html { render :edit }
          end
        end

        format.html { redirect_to @survey, notice: "Pesquisa criada com sucesso" }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_person
    person_id = params[:person_id]

    person = Person.find(person_id.to_i)
    enforcement = @survey.enforcements.create(person_id: person.id)

    respond_to do |format|
      unless enforcement.save
        @survey.errors.messages[:email].append("#{person.email} já está sendo utilizado para esta pesquisa")

        format.json { render json: @survey.errors, status: :unprocessable_entity }
        format.html { render :edit }
      else
        format.json { render json: { enforcement_id: enforcement.id, person: person } }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    # @people_attrs = survey_params[:people]
    # @people_attrs.delete_if { |email| email.empty? || email.blank? }

    respond_to do |format|
      if @survey.update(survey_params.except(:people))
        format.html { redirect_to @survey, notice: "Pesquisa editada com sucesso" }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Pesquisa deletada com sucesso" }
      format.json { head :no_content }
    end
  end

  def send_mail
    @survey.send_request_mails

    respond_to do |format|
      format.html { redirect_to @survey, notice: "Emails enviados com sucesso" }
      format.json { render :show, status: :ok, location: @survey }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = Survey.find(params[:id])
    @people = @survey.people
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def survey_params
    params.require(:survey).permit(
      :question,
      people: [],
    )
  end

  def check_if_survey_is_closed
    if @survey.closed
      redirect_to @survey, notice: "Não é possível editar uma pesquisa fechada"
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def survey_count(survey_id)
    Survey.find(survey_id).enforcements.where(voted: true).count
  end

  def survey_mean(survey_id)
    @survey = Survey.find(survey_id)
    @total = @survey.enforcements.count
    @survey.grade.to_f / @total
  end

  def enforcement_id(survey, person)
    survey.enforcements.find_by(person_id: person.id).id
  end
end

app/views/surveys/_form.html.slim
= form_with(model: survey, local: true, class: "needs-validation") do |form|
  - if survey.errors.any?
      .alert.alert-warning.alert-dismissible.fade.show[role="alert"]
        = pluralize(survey.errors.count, "erros")
        |  impedindo que o registro seja salvo
        hr/
        ul
          - survey.errors.full_messages.each do |message|
            li
              = message
  .form-group
    label[for="question"]
      | Pergunta
    = form.text_area :question, class: 'form-control'
  .form-group
    - if params[:action] == "new"
      select#people-select-new.form-control
      .form-group
        label[for="people"]
          | Pessoas da pesquisa
        = form.select :people, options_from_collection_for_select(survey.people, 'id', 'email') , {}, {class: 'form-control avoid-clicks', multiple: true, readonly: true}
    - else 
      select#people-select.form-control
      .invalid-feedback#select-feedback
      hr/
      .d-flex.justify-content-center
        .spinner-border#people-edit-loading role="status" 
          span.sr-only Loading...
      ul.list-group#people-edit-list
        - survey.people.each do |person|
          li.list-group-item.d-flex.justify-content-between.align-items-center#person-item
            = person.email
            span.badge.badge-primary.badge-pill.clickable.delete-person enforcement_id="#{enforcement_id(@survey, person)}" excluir
  = button_tag 'Salvar', type: 'submit', class: 'btn btn-primary'

app/views/surveys/edit.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Pesquisas
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Editar Pesquisa
      .card-body
        = render 'form', survey: @survey
      .card-footer
        = link_to 'Voltar', surveys_path, class: 'btn btn-primary mr-2'
        = link_to 'Mostrar', @survey, class: 'btn btn-primary mr-2'

app/views/surveys/index.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Pesquisas
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-body
        .table-responsive
          table.table.table-striped.table-sm
            thead
              tr
                th Pergunta
                th Nota
                th #
            tbody
              - @surveys.each do |survey|
                tr
                  td
                    = survey.question
                  td
                    = survey_mean(survey.id)
                  td
                    = link_to 'Exibir', survey, class: 'btn btn-primary btn-sm mr-2'
                    - unless survey.closed 
                      = link_to 'Editar', edit_survey_path(survey), class: 'btn btn-primary btn-sm mr-2' 
                      = link_to 'Enviar Emails', send_mail_survey_path(survey), class: 'btn btn-primary btn-sm mr-2', method: :post
                    = link_to 'Deletar', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm mr-2'
      .card-footer
        = link_to 'Nova pesquisa', new_survey_path

app/views/surveys/new.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Pesquisas
.row
  .col-xl-12.col-sm-12.mb-4
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Nova Pesquisa
      .card-body
        = render 'form', survey: @survey
      .card-footer
        = link_to 'Voltar', surveys_path, class: 'btn btn-primary mr-2'

app/views/surveys/show.html.slim
.d-sm-flex.align-items-center.justify-content-between.mb-4
  h1.h3.mb-0.text-gray-800
    | Pesquisas
.row
  .col-xl-12.col-sm-12.mb-4
    - if notice
      .card.mb-4.py-3.border-bottom-warning
        .card-body
          = notice
    .card.shadow.mb-4
      .card-header.py-3
        h6.m-0.font-weight-bold.text-primary
          | Visualizando pesquisa
      .card-body
        hr/
        p
          strong
            | Pergunta: 
          = @survey.question
        hr/  
        p
          strong
            | Pessoas na Pesquisa:
          br/ 
          - @people.each do |person|
            = person
            br/
        hr/
        p
          strong
            | Média: 
          = survey_mean(@survey.id)
        hr/
        p
          strong
            | Respostas: 
          = survey_count(@survey.id)
        hr/
        p
          strong
            | Finalizada?: 
          = @survey.closed ? 'Sim' : 'Não'
        hr/
      .card-footer
        = link_to 'Voltar', surveys_path, class: 'btn btn-primary mr-2'
        - unless @survey.closed
          = link_to 'Editar', edit_survey_path(@survey), class: 'btn btn-primary mr-2'
          = link_to 'Enviar Emails', send_mail_survey_path(@survey), class: 'btn btn-primary mr-2', method: :post