config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registration]
  resources :people
  resources :surveys do
    post "add_person", on: :member
    post "send_mail", on: :member
  end

  get "enforcements/edit", to: "enforcements#edit"
  get "enforcements/denied", to: "enforcements#denied"
  patch "enforcements/:id/update", to: "enforcements#update", as: :enforcement
  delete "enforcements/:id/delete", to: "enforcements#destroy", as: :enforcement_destroy

  root "surveys#index"
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title HappyNel
    == csrf_meta_tags
    == csp_meta_tag
    
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body#page-top
    /! Page Wrapper
    #wrapper
      /! Sidebar
      ul#accordionSidebar.navbar-nav.bg-gradient-primary.sidebar.sidebar-dark.accordion
        /! Sidebar - Brand
        a.sidebar-brand.d-flex.align-items-center.justify-content-center href="#" 
          .sidebar-brand-icon.rotate-n-15
            i.fas.fa-laugh-wink
          .sidebar-brand-text.mx-3 HappyNel
          /! Divider
        hr.sidebar-divider.my-0/
        /! Nav Item - Dashboard
        li.nav-item.active
          a.nav-link
            i.fas.fa-fw.fa-tachometer-alt
            span Dashboard
        /! Divider
        hr.sidebar-divider/
        /! Heading
        - if admin_signed_in?
          .sidebar-heading
            | Interface
          /! Nav Item - Pages Collapse Menu
          li.nav-item class=(current_class?(surveys_path))
            == link_to surveys_path, class: "nav-link collapsed" do
              i.fas.fa-fw.fa-cog
              span Minhas Pesquisas
          /! Nav Item - Utilities Collapse Menu
          li.nav-item class=(current_class?(people_path))
            == link_to people_path, class: "nav-link collapsed" do
              i.fas.fa-fw.fa-cog
              span Membros
          li.nav-item
            == link_to destroy_admin_session_path, class: "nav-link collapsed", method: :delete do
              i.fas.fa-fw.fa-cog
              span Sair
        /! End of Sidebar
        /! Content Wrapper
      #content-wrapper.d-flex.flex-column
        #content
          .container-fluid.m-3
            == yield
        footer.sticky-footer.bg-white
          .container.my-auto
            .copyright.text-center.my-auto
              span
                | Copyright © Your Website 2019
    a.scroll-to-top.rounded href="#page-top" 
      i.fas.fa-angle-up

app/views/layouts/devise.html.slim
doctype html
html
  head
    title HappyNel
    == csrf_meta_tags
    == csp_meta_tag
    
    == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    body.bg-gradient-primary
  .container
    .row.justify-content-center
      .col-xl-10.col-lg-12.col-md-9
        .card.o-hidden.border-0.shadow-lg.my-5
          .card-body.p-0
            .row
              == yield